name: Publicação automática
on:  
  # nosso script será executado sempre quando houver push e pull request nas branches destacadas abaixo
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    # sistema operacional da máquina que o Github irá disponibilizar para rodar o nosso script 
    runs-on: ubuntu-latest
    env:
      APP_PATH: /home/ubuntu/dev
      APP_SERVICE_NAME: app.service
      BACKUP_DIR: /home/ubuntu/backups
    # aqui é iniciado o passo a passo para realizar o processo de publicação
    steps:
      - uses: actions/checkout@v3

      - name: Cria um arquivo temporário para a chave privada e altera a permissão do arquivo para que só o dono possa ler e escrever (necessário para chaves)
        run: |
               echo "${{ secrets.KEY }}" > /tmp/private_key
               chmod 600 /tmp/private_key

      - name: Criando a pasta da aplicação e acertando diretório... 
        # StrictHostKeyChecking: desativar prompt 'fingerprint'
        # UserKnownHostsFile: para não salvar a chave
        run: |
               ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
               sudo mkdir -p /home/ubuntu/dev

      - name: Ajustar permissões no servidor de Produção
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} "sudo chown -R ubuntu:ubuntu /home/ubuntu/dev && sudo chmod -R 755 /home/ubuntu/dev"

      - name: Preparar diretórios no servidor
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
          "sudo mkdir -p $APP_PATH $BACKUP_DIR && sudo chown -R ubuntu:ubuntu $APP_PATH $BACKUP_DIR && sudo chmod -R 755 $APP_PATH \
          
      - name: 🔁 Backup da aplicação atual antes do deploy
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} "
            set -e
            # Pula backup se diretório estiver vazio
            if [ -d '$APP_PATH' ] && [ \"\$(ls -A '$APP_PATH' 2>/dev/null)\" ]; then
              TS=\$(date +%Y%m%d%H%M%S)
              FILE=\"$BACKUP_DIR/app-\$TS.tgz\"
              # Compacta conteúdo atual
              tar -czf \"\$FILE\" -C \"$APP_PATH\" .
              # Guarda referência do último backup
              echo \"\$FILE\" > \"$BACKUP_DIR/LAST_BACKUP\"
              # Mantém só os 5 mais recentes
              ls -1t \"$BACKUP_DIR\"/app-*.tgz 2>/dev/null | tail -n +6 | xargs -r rm -f
              echo \"Backup criado em: \$FILE\"
            else
              echo 'APP_PATH vazio - sem backup (primeiro deploy?)'
            fi
          "
                     
      - name: 📦 Transferindo os arquivos da aplicação
        run: |
               scp -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ${{ github.workspace }}/* ubuntu@${{ secrets.HOST }}:/home/ubuntu/dev


      - name: 🔄 Reiniciando o serviço da aplicação
        run: |
               ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
               sudo systemctl restart app.service              

      - name: 🧹 Limpa o arquivo de chave privada após uso
        run: |
           rm /tmp/private_key

      - name: 📢 Enviar mensagem para o Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          AUTHOR: ${{ github.actor }}
        run: |
          curl -H "Content-Type: application/json" \
                 -X POST \
                 -d "{\"content\": \"Deploy realizado com sucesso por **${AUTHOR}**!\"}" \
                 $DISCORD_WEBHOOK     
                 
      - name: ⚠️ Restaurar em caso de falha (rollback)
        if: ${{ failure() }}
        run: |
          echo "Falha detectada. Iniciando restauração do último backup..."
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} "
            set -e
            if [ -f \"$BACKUP_DIR/LAST_BACKUP\" ]; then
              FILE=\$(cat \"$BACKUP_DIR/LAST_BACKUP\")
              if [ -f \"\$FILE\" ]; then
                echo \"Restaurando backup \$FILE para $APP_PATH...\"
                # Limpa conteúdo atual e restaura
                rm -rf \"$APP_PATH\"/*
                tar -xzf \"\$FILE\" -C \"$APP_PATH\"
                # Garante permissões pós-restauração
                chown -R ubuntu:ubuntu \"$APP_PATH\"
                chmod -R 755 \"$APP_PATH\"
                # Reinicia serviço
                sudo systemctl restart $APP_SERVICE_NAME
                sudo systemctl status $APP_SERVICE_NAME --no-pager -l || true
                echo \"Restauração concluída.\"
              else
                echo \"Arquivo de backup não encontrado: \$FILE\"
              fi
            else
              echo 'Nenhum LAST_BACKUP encontrado. Nada a restaurar.'
            fi
          "
